#!/bin/sh
# shellcheck disable=SC1090
. "$(dirname "$0")/_/husky.sh"

# To prevent commitlint failing commits made by semantic-release
if [ -z "$GITHUB_ACTIONS" ]; then
  npx --no-install commitlint --edit "$1"
fi
