# This is a basic workflow to help you get started with Actions

name: Semantic Release

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
  pull_request:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  release:
    # The if statement checks the github.ref context to determine the current
    # branch name; if the name is refs/heads/main, then the subsequent steps are
    # executed.
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: 'lts/*'
      - name: Release
        env:
          # For publishing the package to npm.
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          # For publishing releases & commenting PRs/issues.
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: npx semantic-release
